apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'crossplane'
spec:
  project: default
  source:
    repoURL: 'https://charts.crossplane.io/master/'
    targetRevision: 1.11.0-rc.0.99.g9850b98e
    chart: crossplane
  destination:
    server: 'https://kubernetes.docker.internal:6443'
    namespace: cross
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
