
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'Crossplane-Providers'
spec:
  project: default
  source:
    repoURL: 'https://github.com/itumor/Crossplane.git'
    path: Crossplane-Providers
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.docker.internal:6443'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true